server:
  port: ${SERVER_PORT:8079}
  compression:
    enabled: true
    mime-types:
      - application/javascript
      - application/json
      - application/wasm
      - text/css
      - text/html
      - text/markdown
      - text/plain

spring:
  application:
    name: pingpong-web
  mvc:
    contentnegotiation:
      media-types:
        wasm: application/wasm
        onnx: application/octet-stream
        stl: application/octet-stream
        obj: text/plain
        md: text/markdown
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 3600
          cache-public: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
