name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy
        shell: bash
        run: |
          cd "${DEPLOY_DIR:-$HOME/pingpong}"
          git fetch origin
          git reset --hard origin/main
          docker compose build --quiet
          docker compose up -d --force-recreate
